//
//  Navi48Accel.cpp - the Aux-KC accelerator kext (com.navi48.accelprobe 0.0.7, display name Navi48Accel) of milestone #9, route A; 0.0.5 (G6) overrides Navi48Accelerator::newUserClient (slot 239) so that a type 'N48N' open reaches the bring-up kext's native client through the ops table's ABI-3 native_open (an internal design note "G6 design"); 0.0.3 adds the display pipe of #11; 0.0.4 adds the monitor B framebuffer of M5
//  (Navi48Framebuffer : IOFramebuffer, an internal design note "M5 build spec": matches ONLY a Navi48DisplayNub with Navi48DisplayIndex 1 (the monitor B) or, since 0.0.6, 2 (the monitor A; two personalities, one class),
//  published on demand by the bring-up kext's `fbpublish 2` / `fbpublish 1`, never at boot; it answers from the immutable snapshot of Navi48DisplayOps.h (ABI 2: the per-index geometry) and touches no register).
//  (Navi48DisplayPipe : IOAccelDisplayPipe, an internal design note section 3.4 + the binding "11h.1 RE facts" section), OFF unless the bring-up kext's ops
//  table is ABI 2 with the display flag (boot-arg navi48-metal-disp=1): with an ABI-1 table or the flag clear it behaves exactly as 0.0.2.
//  Design: an internal design note (sections 0-3, 5 and the review MUST-FIX 1-7) + the K3 finding: EVERY rebuild of this kext requires a security approval (Allow click) from the user. An
//  Allow click, so it is THIN and STABLE. Nothing here decides a value: it is the fixed IOAccelerator class graph, the gates (kill switch, the
//  runtime vtable/layout gate) and vtable-shaped trampolines into the versioned ops table of the bring-up kext (Navi48MetalOps.h). See n48accel_pure.h
//  for what stays here and why.
//
//  It matches ONLY a Navi48MetalNub (published on demand by the bring-up kext, never at boot): no PCI match, no IOResources personality, nothing runs
//  at boot except the OSMetaClass registrations of the classes below. It touches no hardware, no PCI config space, no interrupts.
//
#include <IOKit/IOService.h>
#include <IOKit/IOLib.h>
#include <IOKit/IOMemoryDescriptor.h>
#include <IOKit/IORangeAllocator.h>
#include <libkern/c++/OSMetaClass.h>
#include <libkern/c++/OSSymbol.h>
#include <libkern/OSAtomic.h>
#include <pexpert/pexpert.h>
#include <mach/kmod.h>
#include <IOKit/IODeviceMemory.h>
#include <IOKit/pwr_mgt/IOPM.h>

#include "n48accel_pure.h"
#include "n48_tramp.inc"       // generated by gates/gen_tramp.py: the trampoline member declarations / definitions (macros)

// ---- pinned return types of every slot we override or call (MUST-FIX 4). Evidence: the disassembly of AppleParavirtGPU (0x142b78f4 populateAccelConfig,
// 0x142b780e getStampMemory returns the descriptor deviceStart retains, 0x142b6b66 init `testb %al`, 0x142b6bd4 completeBarrier `movb $1,%al`, 0x142c5608
// displayModeWillChange `movb $1,%al`) and of the family callers (slots 84/85/87 and 72/73 callers ignore rax).
#define N48_R_IOGraphicsAccelerator2_271 IOMemoryDescriptor *
#define N48_R_IOGraphicsAccelerator2_273 IOAccelEventMachine2 *
#define N48_R_IOGraphicsAccelerator2_307 IOAccelTask *
#define N48_R_IOGraphicsAccelerator2_314 IOAccelTask *
#define N48_R_IOGraphicsAccelerator2_310 void
#define N48_R_IOGraphicsAccelerator2_312 bool
#define N48_R_IOGraphicsAccelerator2_313 void
#define N48_R_IOGraphicsAccelerator2_320 IOAccelDisplayMachine *
#define N48_R_IOGraphicsAccelerator2_324 void *
#define N48_R_IOGraphicsAccelerator2_325 void *
#define N48_R_IOGraphicsAccelerator2_326 void *
#define N48_R_IOGraphicsAccelerator2_327 IOAccel2DContext2 *
#define N48_R_IOGraphicsAccelerator2_328 void *
#define N48_R_IOGraphicsAccelerator2_332 IOAccelSysMemory *
#define N48_R_IOGraphicsAccelerator2_333 IOAccelVidMemory *
#define N48_R_IOGraphicsAccelerator2_334 IOAccelResource2 *
#define N48_R_IOGraphicsAccelerator2_322 IOAccelSharedUserClient2 *
#define N48_R_IOGraphicsAccelerator2_348 IOAccelCommandQueue *
#define N48_R_IOGraphicsAccelerator2_337 IOAccelMemoryMap *
#define N48_R_IOAccelEventMachine2_35 bool
#define N48_R_IOAccelEventMachine2_72 void
#define N48_R_IOAccelEventMachine2_73 void
#define N48_R_IOAccelEventMachineFast2_84 void
#define N48_R_IOAccelEventMachineFast2_85 void
#define N48_R_IOAccelEventMachineFast2_86 bool
#define N48_R_IOAccelEventMachineFast2_87 void
#define N48_R_IOAccelDisplayMachine_269 bool
#define N48_R_IOAccelDisplayMachine_270 bool
#define N48_R_IOAccelMemoryMap_46 bool
#define N48_R_IOAccelMemoryMap_47 bool
#define N48_R_IOAccelMemoryMap_48 bool
// aux 0.0.3 (the display pipe): 11h.1 correction 2 (slot 267 returns an IOAccelMemory object pointer: the caller at 0x145cc4f2 tests rax and uses it as an object);
// isTransactionComplete a bool (pipeshim's proven dpg_isComplete returns bool true); submitTransaction an IOReturn (the base returns txn+0x58 or 0xE0014042, u32);
// newDisplayPipe the pipe object (0x145c075c: operator new(0x318) + the constructor, returned in rax). performTransaction (277) has no generated signature: see
// n48_dp_perform. IOAccelDisplayMachine::start (267) is NOT pinned: we only pass the family's own return value through, untouched, whatever its width.
#define N48_R_IOGraphicsAccelerator2_329 IOAccelDisplayPipe *
#define N48_R_IOAccelDisplayPipe_267 void *
#define N48_R_IOAccelDisplayPipe_278 bool
#define N48_R_IOAccelDisplayPipe_279 IOReturn
#include "IOAccelFamily2_decl.h"   // generated by tools/native/ioaccel-layout/gen_header.py (gates A/B/C below prove it)

using namespace n48accel;

#define N48_LOG(fmt, ...) IOLog("n48accel: " fmt "\n", ##__VA_ARGS__)

// ---- state (one accelerator per boot) --------------------------------------------------------------------------------------------------------
static const N48MetalOps *gOps;          // valid (ops_check ok) or NULL
static void *gCtx;                       // the bring-up kext's per-device state (device_open)
static volatile int32_t gGateState;      // 0 unchecked, 1 PASS, 2 FAIL (fail closed: probe refuses for the rest of the boot)

// ---- kill switch (MUST-FIX 5): the first statement of every entry point ------------------------------------------------------------------------
static bool n48_aux_on() {
	uint32_t v = 0;
	const bool present = PE_parse_boot_argn("navi48-aux", &v, sizeof(v));
	return aux_enabled(present, v);
}
#define N48_AUX_ENTER(ret) do { if (!n48_aux_on()) return ret; } while (0)
#define N48_AUX_ENTER_V() do { if (!n48_aux_on()) return; } while (0)

static inline void n48_trace(uint32_t ev, uint64_t a = 0, uint64_t b = 0) { if (gOps && gOps->trace) gOps->trace(ev, a, b); }

// the generic virtual hook (Navi48MetalOps.h vhook): returns true when the bring-up kext handled the slot (*r = its return value)
static bool n48_vhook(uint32_t cls, uint32_t slot, void *self, const uint64_t *a, uint32_t n, uint64_t *r) {
	if (!gOps || !gCtx || !gOps->vhook || !cap_has(gOps, N48_CAP_VHOOK)) return false;
	return gOps->vhook(gCtx, cls, slot, self, a, n, r) == 1;
}
// aux 0.0.3: the display-pipe hook (ABI 2 disp_hook), asked by the Navi48DisplayPipe trampolines. Display OFF (disp_enabled false: an ABI-1 table, flag clear, no
// hook) or no device = "not handled", so every pipe slot runs the FAMILY's own implementation, exactly as the family's own pipe object would.
static bool n48_disp_vhook(uint32_t cls, uint32_t slot, void *self, const uint64_t *a, uint32_t n, uint64_t *r) {
	if (!gCtx || !disp_enabled(gOps)) return false;
	return gOps->disp_hook(gCtx, cls, slot, self, a, n, r) == 1;
}

// family symbols that are not virtual and not declared in the generated header (exact exported names, checked by gate B)
extern "C" bool n48_IOAccelTask_init(IOAccelTask *self, IOGraphicsAccelerator2 *accel, unsigned int n, IORangeAllocator **ra)
    __asm__("__ZN11IOAccelTask4initEP22IOGraphicsAccelerator2jPP16IORangeAllocator");
extern "C" void n48_initCfg(IOGraphicsAccelerator2 *self) __asm__("__ZN22IOGraphicsAccelerator225initializeConfigStructureEv");

// ---- the classes ---------------------------------------------------------------------------------------------------------------------------
class Navi48Accelerator : public IOGraphicsAccelerator2 {
	OSDeclareDefaultStructors(Navi48Accelerator)
	N48_FWD_DECLS_IOGraphicsAccelerator2
public:
	IOService *nub;
	void *ctx;
	IOMemoryDescriptor *stampMD;     // not retained here: the bring-up kext owns it
	volatile uint32_t *stampVA;

	IOService *probe(IOService *provider, SInt32 *score) override;
	bool start(IOService *provider) override;
	void free() override;

	N48_R_IOGraphicsAccelerator2_271 getStampMemory(unsigned int *n) override;
	N48_R_IOGraphicsAccelerator2_273 newEventMachine() override;
	N48_R_IOGraphicsAccelerator2_307 createUserGPUTask() override;
	N48_R_IOGraphicsAccelerator2_314 createKernelGPUTask() override;
	N48_R_IOGraphicsAccelerator2_310 populateAccelConfig(IOAccelConfig *cfg) override;
	N48_R_IOGraphicsAccelerator2_312 configureDevice(IOPCIDevice *dev) override;
	N48_R_IOGraphicsAccelerator2_313 teardownDevice(IOPCIDevice *dev) override;
	N48_R_IOGraphicsAccelerator2_320 newDisplayMachine() override;
	N48_R_IOGraphicsAccelerator2_324 newGLContext() override;
	N48_R_IOGraphicsAccelerator2_325 newCLContext() override;
	N48_R_IOGraphicsAccelerator2_326 newSurface() override;
	N48_R_IOGraphicsAccelerator2_327 new2DContext() override;
	N48_R_IOGraphicsAccelerator2_328 newVideoContext() override;
	N48_R_IOGraphicsAccelerator2_332 newSysMemory() override;
	N48_R_IOGraphicsAccelerator2_333 newVidMemory() override;
	N48_R_IOGraphicsAccelerator2_334 newResource() override;
	N48_R_IOGraphicsAccelerator2_337 newMemoryMap() override;
	N48_R_IOGraphicsAccelerator2_322 newSharedUserClient() override;
	N48_R_IOGraphicsAccelerator2_348 newCommandQueue() override;
	N48_R_IOGraphicsAccelerator2_329 newDisplayPipe() override;
	IOReturn newUserClient(task_t owningTask, void *securityID, UInt32 type, IOUserClient **handler) override;   // aux 0.0.5 (G6): slot 239, the 4-argument form (the 5-argument slot 238 is IOService's and reaches this one)
};

class Navi48EventMachine : public IOAccelEventMachineFast2 {
	OSDeclareDefaultStructors(Navi48EventMachine)
	N48_TR_DECLS_Navi48EventMachine
public:
	N48_R_IOAccelEventMachine2_35 init(IOGraphicsAccelerator2 *accel, unsigned int n, int timeout) override;
};

class Navi48Task : public IOAccelTask {
	OSDeclareDefaultStructors(Navi48Task)
public:
	bool setup(IOGraphicsAccelerator2 *accel, uint32_t kind);
};

class Navi48DisplayMachine : public IOAccelDisplayMachine {
	OSDeclareDefaultStructors(Navi48DisplayMachine)
public:
	N48_R_IOAccelDisplayMachine_267 start(IOPCIDevice *provider) override;
	N48_R_IOAccelDisplayMachine_269 displayModeWillChange() override;
	N48_R_IOAccelDisplayMachine_270 displayModeDidChange() override;
};

class Navi48SysMemory : public IOAccelSysMemory {
	OSDeclareDefaultStructors(Navi48SysMemory)
	N48_FWD_DECLS_IOAccelSysMemory
};

class Navi48MemoryMap : public IOAccelMemoryMap {
	OSDeclareDefaultStructors(Navi48MemoryMap)
	N48_FWD_DECLS_IOAccelMemoryMap
public:
	N48_R_IOAccelMemoryMap_46 commitIntoGPUPageTable() override;
	N48_R_IOAccelMemoryMap_47 releaseFromGPUPageTable() override;
	N48_R_IOAccelMemoryMap_48 updateGPUPageTable() override;
};

class Navi48VidMemory : public IOAccelVidMemory {
	OSDeclareDefaultStructors(Navi48VidMemory)
	N48_TR_DECLS_Navi48VidMemory
};
class Navi48Resource : public IOAccelResource2 {
	OSDeclareDefaultStructors(Navi48Resource)
	N48_TR_DECLS_Navi48Resource
};
class Navi482DContext : public IOAccel2DContext2 {
	OSDeclareDefaultStructors(Navi482DContext)
	N48_TR_DECLS_Navi482DContext
};
class Navi48SharedUserClient : public IOAccelSharedUserClient2 {
	OSDeclareDefaultStructors(Navi48SharedUserClient)
	N48_TR_DECLS_Navi48SharedUserClient
};
class Navi48CommandQueue : public IOAccelCommandQueue {
	OSDeclareDefaultStructors(Navi48CommandQueue)
	N48_TR_DECLS_Navi48CommandQueue
};
// aux 0.0.3: the display pipe (M11H section 3.4). No data members (state lives in the bring-up kext): slots 267 / 278 / 279 are generated trampolines into
// n48_disp_vhook (default: the family's own slot), slot 277 is the hand-written thunk below (its generated declaration is the placeholder _vslot277()).
class Navi48DisplayPipe : public IOAccelDisplayPipe {
	OSDeclareDefaultStructors(Navi48DisplayPipe)
	N48_TR_DECLS_Navi48DisplayPipe
public:
	void _vslot277() override;
};

// aux 0.0.4 (M5): the monitor B framebuffer (an internal design note "M5 build spec: Navi48Framebuffer for the monitor B", section 2). A plain IOFramebuffer subclass (the SDK's class, size and slot count proven against the running
// kernel by the generated header's static_assert and the layout gates). Exactly these overrides, nothing else: start (184), getVRAMRange (310), enableController (311), setDisplayMode (319), getStartupDisplayMode (322),
// setAttribute (325), getAttribute (326), getConnectionCount (330), setAttributeForConnection (331), getAttributeForConnection (332), hasDDCConnect (344), getDDCBlock (345) and the pure virtuals getApertureRange (309),
// getPixelFormats (312), getDisplayModeCount (313), getDisplayModes (314), getInformationForDisplayMode (315), getPixelFormatsForDisplayMode (316), getPixelInformation (317), getCurrentDisplayMode (318). isConsoleDevice (305)
// is NOT overridden (the base returns 0); the interrupts (346-348) are super's: no 'vbl ' source. Every answer is a pure function of the snapshot (n48accel_pure.h fb_*).
class Navi48Framebuffer : public IOFramebuffer {
	OSDeclareDefaultStructors(Navi48Framebuffer)
public:
	N48DispSnap snap;                 // copied from the nub's ops table at start(): immutable afterwards
	const N48DispOps *dops;           // the nub's ops table (static in the bring-up kext)
	uint32_t powerState;              // the last power state IOFramebuffer asked for: RECORDED only (M5 has no hardware action)
	uint32_t connPower;               // the last kConnectionPower value: recorded only
	bool pmRegistered;
	void initForPM();                 // RDNA4FB's initForPM (a plain member)

	bool start(IOService *provider) override;
	IODeviceMemory *getApertureRange(IOPixelAperture aperture) override;
	IODeviceMemory *getVRAMRange() override;
	IOReturn enableController() override;
	const char *getPixelFormats() override;
	IOItemCount getDisplayModeCount() override;
	IOReturn getDisplayModes(IODisplayModeID *allDisplayModes) override;
	IOReturn getInformationForDisplayMode(IODisplayModeID displayMode, IODisplayModeInformation *info) override;
	UInt64 getPixelFormatsForDisplayMode(IODisplayModeID displayMode, IOIndex depth) override;
	IOReturn getPixelInformation(IODisplayModeID displayMode, IOIndex depth, IOPixelAperture aperture, IOPixelInformation *pixelInfo) override;
	IOReturn getCurrentDisplayMode(IODisplayModeID *displayMode, IOIndex *depth) override;
	IOReturn setDisplayMode(IODisplayModeID displayMode, IOIndex depth) override;
	IOReturn getStartupDisplayMode(IODisplayModeID *displayMode, IOIndex *depth) override;
	IOReturn setAttribute(IOSelect attribute, uintptr_t value) override;
	IOReturn getAttribute(IOSelect attribute, uintptr_t *value) override;
	IOItemCount getConnectionCount() override;
	IOReturn setAttributeForConnection(IOIndex connectIndex, IOSelect attribute, uintptr_t value) override;
	IOReturn getAttributeForConnection(IOIndex connectIndex, IOSelect attribute, uintptr_t *value) override;
	bool hasDDCConnect(IOIndex connectIndex) override;
	IOReturn getDDCBlock(IOIndex connectIndex, UInt32 blockNumber, IOSelect blockType, IOOptionBits options, UInt8 *data, IOByteCount *length) override;
};

#define N48_META(C, S) OSDefineMetaClassAndStructors(C, S) \
	static_assert(sizeof(C) >= N48_##S##_SIZE, "leaf class smaller than its family parent");
N48_META(Navi48Accelerator, IOGraphicsAccelerator2)
N48_META(Navi48EventMachine, IOAccelEventMachineFast2)
N48_META(Navi48Task, IOAccelTask)
N48_META(Navi48DisplayMachine, IOAccelDisplayMachine)
N48_META(Navi48SysMemory, IOAccelSysMemory)
N48_META(Navi48MemoryMap, IOAccelMemoryMap)
N48_META(Navi48VidMemory, IOAccelVidMemory)
N48_META(Navi48Resource, IOAccelResource2)
N48_META(Navi482DContext, IOAccel2DContext2)
N48_META(Navi48SharedUserClient, IOAccelSharedUserClient2)
N48_META(Navi48CommandQueue, IOAccelCommandQueue)
N48_META(Navi48DisplayPipe, IOAccelDisplayPipe)
N48_META(Navi48Framebuffer, IOFramebuffer)

// forwarders for the slots whose family symbol is not exported (generated: N48_FWD_DEFS_<Parent>): naked tail-jumps into the parent's own vtable slot
N48_FWD_DEFS_IOGraphicsAccelerator2(Navi48Accelerator)
N48_FWD_DEFS_IOAccelSysMemory(Navi48SysMemory)
N48_FWD_DEFS_IOAccelMemoryMap(Navi48MemoryMap)

// ---- the runtime layout gate (MUST-FIX 3) --------------------------------------------------------------------------------------------------
// The tables (vtable symbols of our classes and of the family's, override slot lists, expected sizes) are generated by gates/gen_gate.py from the same
// model that produced the header, and gate A proves the linked kext's defined slots equal those lists.
namespace {
struct ClassGate { const char *ours; const char *fam; const uintptr_t *ztvOurs; const uintptr_t *ztvFam; uint32_t nslots; const uint16_t *ovr; uint32_t novr; uint32_t ourSize; uint32_t famSize; const OSMetaClass *ourMeta; };
}
#include "n48_gate.inc"

N48_TR_DEFS_Navi48EventMachine(Navi48EventMachine)
N48_TR_DEFS_Navi48VidMemory(Navi48VidMemory)
N48_TR_DEFS_Navi48Resource(Navi48Resource)
N48_TR_DEFS_Navi482DContext(Navi482DContext)
N48_TR_DEFS_Navi48SharedUserClient(Navi48SharedUserClient)
N48_TR_DEFS_Navi48CommandQueue(Navi48CommandQueue)
N48_TR_DEFS_Navi48DisplayPipe(Navi48DisplayPipe)

// Slot 277 performTransaction(IOAccelDisplayPipeTransaction2*) (family symbol __ZN18IOAccelDisplayPipe18performTransactionEP30IOAccelDisplayPipeTransaction2, vtables/
// IOAccelDisplayPipe.tsv row 277; the argument list is that mangled name's). The generated header declares the slot as `void _vslot277()`, so the override is a
// naked tail jump: rdi (this) and rsi (the transaction) arrive untouched in n48_dp_perform, which returns in rax what the family's caller reads (an IOReturn in
// eax; the base returns 0xE00002C7). Same trampoline contract as the generated ones: kill switch first, then the display hook, else the family's own slot.
extern "C" __attribute__((used, visibility("hidden"))) uint64_t n48_dp_perform(Navi48DisplayPipe *self, IOAccelDisplayPipeTransaction2 *txn) {
	N48_AUX_ENTER((uint64_t)0);
	uint64_t a[6] = { (uint64_t)(uintptr_t)txn, 0, 0, 0, 0, 0 }; uint64_t r = 0;
	if (n48_disp_vhook(N48_VC_DISPLAYPIPE, 277, (void *)self, a, 1, &r)) return r;
	return ((uint64_t (*)(Navi48DisplayPipe *, IOAccelDisplayPipeTransaction2 *))(n48_ztvfam_IOAccelDisplayPipe[2 + 277]))(self, txn);
}
__attribute__((naked)) void Navi48DisplayPipe::_vslot277() { __asm__("jmp _n48_dp_perform"); }

extern "C" kmod_info_t kmod_info;   // kmod_info.c (KMOD_EXPLICIT_DECL)
static uintptr_t n48_anchor() { return (uintptr_t)&n48_anchor; }

static bool n48_layout_gate() {
	if (gGateState) return gGateState == 1;
	uintptr_t lo = 0, hi = 0;
	const bool kw = text_window(n48_anchor(), (uintptr_t)kmod_info.address, (uintptr_t)kmod_info.size, &lo, &hi);   // our own image range (kmod_info), else +-4 MiB around a function of ours
	N48_LOG("layout window: %s [%#lx, %#lx)", kw ? "kmod_info" : "fallback", (unsigned long)lo, (unsigned long)hi);
	uint32_t total = 0, want = 0;
	bool ok = true;
	for (const ClassGate &g : kGate) {
		want += g.nslots;
		// class sizes: the family's registered metaclass must have the size the header was built for; ours is sizeof(our class)
		const OSSymbol *s = OSSymbol::withCString(g.fam);
		const OSMetaClass *fm = s ? OSMetaClass::getMetaClassWithName(s) : nullptr;
		if (s) s->release();
		if (!fm || !size_ok((uint32_t)fm->getClassSize(), g.famSize)) {
			N48_LOG("layout FAIL class %s: family size %u, expected %u", g.fam, fm ? (unsigned)fm->getClassSize() : 0u, g.famSize);
			ok = false; break;
		}
		if (!g.ourMeta || !size_ok((uint32_t)g.ourMeta->getClassSize(), g.ourSize)) { N48_LOG("layout FAIL class %s: own size mismatch", g.ours); ok = false; break; }
		const GateResult r = gate_compare(g.ztvOurs + 2, g.ztvFam + 2, g.nslots, g.ovr, g.novr, lo, hi);   // slot 0 sits at the vtable symbol + 16
		if (r.v != kGateOk) {
			N48_LOG("layout FAIL class %s slot %u verdict %u ours %#llx family %#llx", g.ours, r.slot, (unsigned)r.v, (unsigned long long)r.ours, (unsigned long long)r.fam);
			ok = false; break;
		}
		total += r.compared;
		N48_LOG("layout %s vs %s: MATCH (%u slots, %u overrides, size %#x)", g.ours, g.fam, g.nslots, g.novr, g.famSize);
	}
	if (ok) N48_LOG("layout PASS %u/%u", total, want);
	OSCompareAndSwap(0, ok ? 1 : 2, &gGateState);
	return gGateState == 1;
}

// ---- ops acquisition -----------------------------------------------------------------------------------------------------------------------------
static const N48MetalOps *n48_get_ops(IOService *nub) {
	if (!nub) return nullptr;
	const OSSymbol *fn = OSSymbol::withCString(N48_METAL_FN_SYMBOL);
	if (!fn) return nullptr;
	const N48MetalOps *o = nullptr;
	const IOReturn rc = nub->callPlatformFunction(fn, /*waitForFunction=*/false, (void *)&o, nullptr, nullptr, nullptr);
	fn->release();
	if (rc != kIOReturnSuccess) { N48_LOG("ops: callPlatformFunction rc %#x", (unsigned)rc); return nullptr; }
	const OpsVerdict v = ops_check(o);
	if (v != kOpsOk) { N48_LOG("ops: refused (verdict %u)", (unsigned)v); return nullptr; }
	return o;
}
static bool n48_provider_is_nub(IOService *p) {
	const OSMetaClass *mc = p ? p->getMetaClass() : nullptr;
	const char *nm = mc ? mc->getClassName() : nullptr;
	if (!nm) return false;
	const char *want = N48_METAL_NUB_CLASS;
	for (; *want; ++want, ++nm) if (*want != *nm) return false;
	return *nm == 0;
}

// ---- Navi48Accelerator ------------------------------------------------------------------------------------------------------------------------
IOService *Navi48Accelerator::probe(IOService *provider, SInt32 *score) {
	N48_AUX_ENTER(nullptr);
	if (!n48_provider_is_nub(provider)) return nullptr;      // nub only: never a PCI device
	if (!n48_layout_gate()) return nullptr;                  // fail closed
	const N48MetalOps *o = n48_get_ops(provider);
	if (!o) return nullptr;
	// Static config check against the FAMILY'S OWN defaults, before anything can reach IOSurfaceRoot::updateLimits: run its initializeConfigStructure()
	// (a plain field initialiser; start() does it again) and the bring-up kext's populate hook on top; a non-zero result refuses the match.
	n48_initCfg(this);
	uint8_t *cfg = (uint8_t *)this + 0xc88;
	if (o->populate_config(cfg, 0x90u) != 0) { N48_LOG("probe: config static check refused"); return nullptr; }
	gOps = o;
	n48_trace(N48_TR_PROBE_OK, (uint64_t)(uintptr_t)this);
	return IOService::probe(provider, score);
}

bool Navi48Accelerator::start(IOService *provider) {
	N48_AUX_ENTER(false);
	if (!gOps || !n48_provider_is_nub(provider) || gGateState != 1) return false;   // probe did the work; never start unproven
	const bool ok = IOGraphicsAccelerator2::start(provider);
	if (ok) registerService();                                                     // AppleParavirtAccelerator::start does the same
	n48_trace(N48_TR_STARTED, ok, (uint64_t)(uintptr_t)this);
	return ok;
}

void Navi48Accelerator::free() {
	if (ctx && gOps) { gOps->device_close(ctx); if (gCtx == ctx) gCtx = nullptr; ctx = nullptr; stampMD = nullptr; stampVA = nullptr; }   // idempotent; the family's stop normally got here first
	IOGraphicsAccelerator2::free();
}

bool Navi48Accelerator::configureDevice(IOPCIDevice *) {
	N48_AUX_ENTER(false);
	IOService *p = getProvider();
	if (!gOps || !p || !n48_provider_is_nub(p) || ctx) return false;
	void *c = gOps->device_open(this, p);
	if (!c) return false;
	ctx = c; nub = p; gCtx = c;
	stampMD = (IOMemoryDescriptor *)gOps->stamp_memory(c, nullptr);
	stampVA = gOps->stamp_va(c);
	n48_trace(N48_TR_DEVICE_OPEN, (uint64_t)(uintptr_t)c);
	if (!stampMD || !stampVA) { gOps->device_close(c); ctx = nullptr; gCtx = nullptr; stampMD = nullptr; stampVA = nullptr; return false; }
	return true;
}

void Navi48Accelerator::teardownDevice(IOPCIDevice *) {     // tolerates a NULL argument and a half-configured device
	if (ctx && gOps) { n48_trace(N48_TR_DEVICE_CLOSE, (uint64_t)(uintptr_t)ctx); gOps->device_close(ctx); }
	ctx = nullptr; gCtx = nullptr; stampMD = nullptr; stampVA = nullptr;
}

static const char kFallbackName[] = "n48accel";   // a static NON-NULL name: IOAccelDevice2::get_name strncpy's cfg->name (a NULL name would fault)

void Navi48Accelerator::populateAccelConfig(IOAccelConfig *cfg) {
	N48_AUX_ENTER_V();
	uint8_t *c = (uint8_t *)cfg;
	const int rc = (gOps && cfg) ? gOps->populate_config(c, 0x90u) : -1;
	n48_trace(N48_TR_POPULATE, (uint64_t)(int64_t)rc);
	if (!config_keep(gOps != nullptr, rc) && c) {
		// Fail closed WITHOUT a NULL name (validateConfigStructure is never called in start): keep the family defaults (non-zero IOSurface limits), a static name, and
		// tear the device down so the event machine's init finds no stamp VA and fails, which aborts the family's start.
		const uint64_t np = (uint64_t)(uintptr_t)kFallbackName;
		for (int i = 0; i < 8; ++i) c[i] = (uint8_t)(np >> (8 * i));
		if (ctx && gOps) { gOps->device_close(ctx); }
		if (gCtx == ctx) gCtx = nullptr;
		ctx = nullptr; stampMD = nullptr; stampVA = nullptr;
	}
}

IOMemoryDescriptor *Navi48Accelerator::getStampMemory(unsigned int *n) {
	N48_AUX_ENTER(nullptr);
	if (n) *n = 0;
	unsigned int nn = 0;
	IOMemoryDescriptor *md = (ctx && gOps) ? (IOMemoryDescriptor *)gOps->stamp_memory(ctx, &nn) : nullptr;   // NOT retained (deviceStart retains it)
	if (n) *n = nn;
	n48_trace(N48_TR_STAMP, (uint64_t)(uintptr_t)md, nn);
	return md;
}

IOAccelEventMachine2 *Navi48Accelerator::newEventMachine() {
	N48_AUX_ENTER(nullptr);
	return OSTypeAlloc(Navi48EventMachine);     // the family calls init() (below) right after: Fast2 init FIRST, then the stamp base
}

IOAccelTask *Navi48Accelerator::createUserGPUTask() {
	N48_AUX_ENTER(nullptr);
	Navi48Task *t = OSTypeAlloc(Navi48Task);
	if (!t) return nullptr;
	if (!t->setup(this, 0u)) { t->release(); return nullptr; }
	return t;
}
IOAccelTask *Navi48Accelerator::createKernelGPUTask() {
	N48_AUX_ENTER(nullptr);
	Navi48Task *t = OSTypeAlloc(Navi48Task);
	if (!t) return nullptr;
	if (!t->setup(this, 1u)) { t->release(); return nullptr; }
	return t;
}

IOAccelDisplayMachine *Navi48Accelerator::newDisplayMachine() {
	N48_AUX_ENTER(nullptr);
	n48_trace(N48_TR_DISPLAY);
	return OSTypeAlloc(Navi48DisplayMachine);    // the family's init / start / stop are inherited unchanged; only the two pure hooks are ours
}

// factories with no class in this build, or gated by the bring-up kext: NULL
void *Navi48Accelerator::newGLContext()    { N48_AUX_ENTER(nullptr); n48_trace(N48_TR_STUB, 324); return nullptr; }
void *Navi48Accelerator::newCLContext()    { N48_AUX_ENTER(nullptr); n48_trace(N48_TR_STUB, 325); return nullptr; }
void *Navi48Accelerator::newSurface()      { N48_AUX_ENTER(nullptr); n48_trace(N48_TR_STUB, 326); return nullptr; }
void *Navi48Accelerator::newVideoContext() { N48_AUX_ENTER(nullptr); n48_trace(N48_TR_STUB, 328); return nullptr; }
// Optional classes: created only when the bring-up kext's factory mask allows it (default 0 = NULL, exactly the paravirt / pre-hook behaviour).
static bool n48_fact(Navi48Accelerator *a, uint32_t bit, uint32_t kind) {
	const uint32_t m = (a->ctx && gOps && gOps->factory_mask) ? gOps->factory_mask(a->ctx) : 0u;
	const bool ok = factory_allowed(gOps != nullptr, m, bit);
	n48_trace(N48_TR_FACTORY, kind, ok);
	return ok;
}
IOAccel2DContext2 *Navi48Accelerator::new2DContext()  { N48_AUX_ENTER(nullptr); return n48_fact(this, N48_FACT_CTX2D, 327) ? OSTypeAlloc(Navi482DContext) : nullptr; }
IOAccelVidMemory *Navi48Accelerator::newVidMemory()   { N48_AUX_ENTER(nullptr); return n48_fact(this, N48_FACT_VIDMEMORY, 333) ? OSTypeAlloc(Navi48VidMemory) : nullptr; }
IOAccelResource2 *Navi48Accelerator::newResource()    { N48_AUX_ENTER(nullptr); return n48_fact(this, N48_FACT_RESOURCE, 334) ? OSTypeAlloc(Navi48Resource) : nullptr; }
// The family's own (non-pure) factories: the aux subclass only when allowed, otherwise the family's own object, exactly as if we did not override.
IOAccelSharedUserClient2 *Navi48Accelerator::newSharedUserClient() {
	N48_AUX_ENTER(nullptr);
	return n48_fact(this, N48_FACT_SHAREDUC, 322) ? OSTypeAlloc(Navi48SharedUserClient) : (IOAccelSharedUserClient2 *)IOGraphicsAccelerator2::newSharedUserClient();
}
IOAccelCommandQueue *Navi48Accelerator::newCommandQueue() {
	N48_AUX_ENTER(nullptr);
	return n48_fact(this, N48_FACT_CMDQUEUE, 348) ? OSTypeAlloc(Navi48CommandQueue) : (IOAccelCommandQueue *)IOGraphicsAccelerator2::newCommandQueue();
}
IOAccelSysMemory *Navi48Accelerator::newSysMemory() {
	N48_AUX_ENTER(nullptr);
	const uint32_t m = (ctx && gOps && gOps->factory_mask) ? gOps->factory_mask(ctx) : 0u;
	const bool ok = factory_allowed(gOps != nullptr, m, N48_FACT_SYSMEMORY);
	n48_trace(N48_TR_FACTORY, 332, ok);
	return ok ? OSTypeAlloc(Navi48SysMemory) : nullptr;
}
// aux 0.0.3 (M11H section 3.4, slot 329): with display on, a Navi48DisplayPipe (allocated and constructed; the family's createDisplayPipe calls init on it,
// exactly as it does on its own object); display off, or our allocation failed: the family's own IOGraphicsAccelerator2::newDisplayPipe (0.0.2 behaviour).
// Never NULL from us: found_framebuffer stores the result without a check (11h.1 correction 4).
IOAccelDisplayPipe *Navi48Accelerator::newDisplayPipe() {
	N48_AUX_ENTER(IOGraphicsAccelerator2::newDisplayPipe());
	const bool on = disp_enabled(gOps);
	Navi48DisplayPipe *mine = on ? OSTypeAlloc(Navi48DisplayPipe) : nullptr;
	const bool ours = pipe_choice(on, mine != nullptr) == kPipeOurs;
	IOAccelDisplayPipe *p = ours ? (IOAccelDisplayPipe *)mine : IOGraphicsAccelerator2::newDisplayPipe();
	n48_trace(N48_TR_DISPPIPE, (uint64_t)(uintptr_t)p, ours ? 1u : 0u);
	return p;
}
// aux 0.0.5 (G6, an internal design note "G6 design" section 2): slot 239 of the family (IOGraphicsAccelerator2::newUserClient). Type 'N48N' is the bring-up kext's native client, attached to THIS accelerator so that a
// sandboxed application (whose profile admits user clients on an IOAccelerator service) can open it. It is decided HERE, before the family's per-PID client limits and its 0x9bc bookkeeping, and an 'N48N' open NEVER reaches the
// family (the family would hand an unknown type to newContext and give the caller a generic IOAccelContext2): kill switch off, gate not passed, no usable hook = kIOReturnUnsupported. Every other type is the family's, untouched.
// The hook returns an IOReturn: it is compared with kIoSuccess (nuc_result), never read as a bool (vhook's "1 = handled" convention does not apply).
IOReturn Navi48Accelerator::newUserClient(task_t owningTask, void *securityID, UInt32 type, IOUserClient **handler) {
	N48_AUX_ENTER(type == N48_METAL_UC_N48N ? kIOReturnUnsupported : IOGraphicsAccelerator2::newUserClient(owningTask, securityID, type, handler));
	const NucPlan plan = nuc_plan(type, true, gGateState == 1, gOps, ctx != nullptr && ctx == gCtx);
	if (plan == kNucFamily) return IOGraphicsAccelerator2::newUserClient(owningTask, securityID, type, handler);
	if (handler) *handler = nullptr;
	if (plan != kNucNative) return kIOReturnUnsupported;
	if (!handler) return kIOReturnBadArgument;
	IOUserClient *uc = nullptr;
	const int32_t rc = gOps->native_open(ctx, this, (void *)owningTask, securityID, type, (void **)&uc);
	const int32_t out = nuc_result(rc, uc != nullptr);
	if (out == kIoSuccess) *handler = uc;
	else if (uc) { uc->release(); uc = nullptr; }   // a refusal never leaves an object behind (the hook returns none; this is belt and braces)
	n48_trace(N48_TR_NATIVE_OPEN, (uint64_t)(uint32_t)out, (uint64_t)(uintptr_t)uc);
	return (IOReturn)out;
}
IOAccelMemoryMap *Navi48Accelerator::newMemoryMap() {
	N48_AUX_ENTER(nullptr);
	const uint32_t m = (ctx && gOps && gOps->factory_mask) ? gOps->factory_mask(ctx) : 0u;
	const bool ok = factory_allowed(gOps != nullptr, m, N48_FACT_MEMORYMAP);
	n48_trace(N48_TR_FACTORY, 337, ok);
	return ok ? OSTypeAlloc(Navi48MemoryMap) : nullptr;
}

// ---- Navi48EventMachine -----------------------------------------------------------------------------------------------------------------------
bool Navi48EventMachine::init(IOGraphicsAccelerator2 *accel, unsigned int n, int timeout) {
	N48_AUX_ENTER(false);
	const bool sup = IOAccelEventMachineFast2::init(accel, n, timeout);          // FIRST (MUST-FIX 2)
	Navi48Accelerator *na = OSDynamicCast(Navi48Accelerator, accel);
	volatile uint32_t *va = na ? na->stampVA : nullptr;
	const EmPlan p = em_init_plan(sup, va != nullptr);
	if (p.ok) {
		typedef void (*SetStamp)(IOAccelEventMachine2 *, volatile uint32_t *);
		((SetStamp)(*(void ***)this)[38])(this, va);                               // slot 38 = setStampBaseAddress(unsigned volatile*), as paravirt's init does
	}
	n48_trace(N48_TR_EM_INIT, p.ok, sup);
	return p.ok;
}

// ---- Navi48Task -------------------------------------------------------------------------------------------------------------------------------
// AppleParavirtTask::init (0x142b85b6): IORangeAllocator::init(size-1, 0x1000, 0x400, 0), allocateRange(0, 0x1000) (page 0 reserved), then
// IOAccelTask::init(accel, 1, &ra) and a release of whatever the callee left in ra.
bool Navi48Task::setup(IOGraphicsAccelerator2 *accel, uint32_t kind) {
	N48_AUX_ENTER(false);
	uint64_t size = 0, reserve = 0;
	if (!gOps || !gCtx || gOps->task_window(gCtx, kind, &size, &reserve) != 0 || !task_window_ok(size, reserve)) return false;
	IORangeAllocator *ra = IORangeAllocator::withRange((IORangeScalar)(size - 1), kPage, 0x400u, 0);
	if (!ra) return false;
	if (reserve && !ra->allocateRange(0, (IORangeScalar)reserve)) { ra->release(); return false; }
	const bool ok = n48_IOAccelTask_init(this, accel, 1u, &ra);
	if (ra) ra->release();
	n48_trace(N48_TR_TASK, kind, ok);
	return ok;
}

// ---- Navi48DisplayMachine ---------------------------------------------------------------------------------------------------------------------
// aux 0.0.3 (M11H section 3.2 option C). IOGraphicsAccelerator2::requestProbe(1) calls this with accel+0x368, the provider cast at start, which for us is the
// Navi48MetalNub. The family's framebuffer discovery walk only looks at the children and clients of that argument (getChildIterator /
// copyClientWithCategory("IOFramebuffer") / getClientIterator, M11H section 3.2 and 11h.1 F4), and the nub has no framebuffer below it: RDNA4FB is attached to
// the GPU's IOPCIDevice, a sibling of the bring-up kext. So with display on and a nub argument, the walk starts at the PCI device the bring-up kext hands us
// (ops pci_device); every other case passes the family's own argument through (0.0.2). The walk makes IOService virtual calls only (no PCI config access).
N48_R_IOAccelDisplayMachine_267 Navi48DisplayMachine::start(IOPCIDevice *provider) {
	N48_AUX_ENTER(IOAccelDisplayMachine::start(provider));
	const bool on = disp_enabled(gOps);
	void *pci = (on && gCtx && gOps->pci_device) ? gOps->pci_device(gCtx) : nullptr;
	void *use = dm_walk_provider(on, n48_provider_is_nub((IOService *)(void *)provider), (void *)provider, pci);
	n48_trace(N48_TR_DM_START, (uint64_t)(uintptr_t)use, use != (void *)provider ? 1u : 0u);
	return IOAccelDisplayMachine::start((IOPCIDevice *)use);
}
bool Navi48DisplayMachine::displayModeWillChange() { return true; }   // AppleParavirtDisplayMachine 0x142c5608: `movb $1,%al`
bool Navi48DisplayMachine::displayModeDidChange()  { return true; }

// ---- Navi48MemoryMap (only ever created when the bring-up kext enables N48_FACT_MEMORYMAP) ------------------------------------------------------
static bool n48_mm(uint32_t op, void *obj) {
	const bool have = gOps && gOps->mm_hook && gCtx;
	const int rc = have ? gOps->mm_hook(gCtx, op, obj) : -1;
	n48_trace(N48_TR_MM, op, (uint64_t)(int64_t)rc);
	return mm_result(gOps != nullptr, have, rc);
}
bool Navi48MemoryMap::commitIntoGPUPageTable()   { N48_AUX_ENTER(false); return n48_mm(N48_MM_COMMIT, this); }
bool Navi48MemoryMap::releaseFromGPUPageTable()  { N48_AUX_ENTER(false); return n48_mm(N48_MM_RELEASE, this); }
bool Navi48MemoryMap::updateGPUPageTable()       { N48_AUX_ENTER(false); return n48_mm(N48_MM_UPDATE, this); }

// ---- Navi48Framebuffer (aux 0.0.4, M5) ----------------------------------------------------------------------------------------------------------------------------------------------------
// Adapted from RDNA4FB's AMDRDNA4FB (src/RDNA4FB/src/framebuffer.cpp:1908-1941 initForPM, :2194-2442 the IOFramebuffer overrides; BSD-3-Clause, (c) the RDNA4FB authors): the overrides keep RDNA4FB's contract and answers, with the
// console geometry replaced by the immutable snapshot of Navi48DisplayOps.h. The framebuffer is a client of Navi48DisplayNub, which the bring-up kext publishes ONLY on demand (`fbpublish 2`), never at boot.
static_assert(kFbAttrEnable == kConnectionEnable && kFbAttrCheckEnable == kConnectionCheckEnable && kFbAttrFlags == kConnectionFlags && kFbAttrHlDdc == kConnectionSupportsHLDDCSense && kFbAttrPower == kConnectionPower &&
              kFbAttrPower == kIOPowerAttribute && kFbAttrCursor == kIOHardwareCursorAttribute, "the pure header's four-character codes are IOKit's");
static_assert(kFbModeId == 1u, "one mode, id 1");

static bool n48_is_class(IOService *p, const char *want) {
	const OSMetaClass *mc = p ? p->getMetaClass() : nullptr;
	const char *nm = mc ? mc->getClassName() : nullptr;
	if (!nm) return false;
	for (; *want; ++want, ++nm) if (*want != *nm) return false;
	return *nm == 0;
}
static const N48DispOps *n48_get_dops(IOService *nub) {
	if (!nub) return nullptr;
	const OSSymbol *fn = OSSymbol::withCString(N48_DISP_FN_SYMBOL);
	if (!fn) return nullptr;
	const N48DispOps *o = nullptr;
	const IOReturn rc = nub->callPlatformFunction(fn, /*waitForFunction=*/false, (void *)&o, nullptr, nullptr, nullptr);
	fn->release();
	return rc == kIOReturnSuccess ? o : nullptr;
}

// 0.0.6: the display index of the nub (its Navi48DisplayIndex OSNumber, the very property the personality matched on): 1 = the monitor B, 2 = the monitor A; 0 = none / unknown
static uint32_t n48_provider_index(IOService *nub) {
	OSNumber *n = nub ? OSDynamicCast(OSNumber, nub->getProperty(N48_DISP_INDEX_KEY)) : nullptr;
	return fb_provider_index(n != nullptr, n ? (uint64_t)n->unsigned64BitValue() : 0u);
}

bool Navi48Framebuffer::start(IOService *provider) {
	N48_AUX_ENTER(false);
	uint32_t wsv = 0, m6v = 0;
	const bool metalWsArg = PE_parse_boot_argn("navi48-metal-ws", &wsv, sizeof(wsv));      // present with ANY value: that boot gives the DP to the GPU desktop
	const bool m6On = m6_on(PE_parse_boot_argn("navi48-m6", &m6v, sizeof(m6v)), m6v);       // 0.0.7 (M6 Stage 1a, R1): navi48-m6=1 lifts the refusal (the bring-up kext's routing guard replaces it)
	const bool metalWs = fb_metal_ws_blocks(metalWsArg, m6On);                                // what the verdict below judges: metal-ws present AND the M6 latch OFF
	const bool isNub = n48_is_class(provider, N48_DISP_NUB_CLASS);
	const bool layoutOk = !metalWs && isNub && n48_layout_gate();         // the runtime layout gate runs HERE too: on an fb2 boot no accelerator is probed (the gate's other caller), and the framebuffer must never start unproven
	const N48DispOps *o = layoutOk ? n48_get_dops(provider) : nullptr;
	const uint32_t pidx = n48_provider_index(provider);                   // 0.0.6: which display this nub is (1 = the monitor B, 2 = the monitor A)
	const uint32_t ov = layoutOk ? n48disp_ops_check_for(o, pidx) : (uint32_t)N48_DOV_NULL;      // index 2 needs an ABI-2 table: an ABI-1 bring-up kext is refused here
	N48DispSnap s;
	bzero(&s, sizeof(s));
	const int rc = ov == N48_DOV_OK ? o->snapshot((void *)provider, &s) : -1;
	const uint32_t sv = rc == 0 ? fb_snap_for_index(&s, pidx) : (uint32_t)N48_DSV_NULL;      // valid for ITS OWN index's geometry and carrying exactly that index
	const FbStart v = fb_start_verdict(n48_aux_on(), metalWs, isNub, layoutOk, ov, rc, sv);
	if (o && ov == N48_DOV_OK && o->trace) o->trace(v == kFbStartOk ? N48_DTR_START_OK : N48_DTR_START_REFUSED, (uint64_t)v, ((uint64_t)ov << 32) | sv);
	if (v != kFbStartOk) return false;
	snap = s; dops = o; powerState = 2u; connPower = 1u; pmRegistered = false;
	const bool ok = IOFramebuffer::start(provider);
	if (o->trace) o->trace(ok ? N48_DTR_START_OK : N48_DTR_START_REFUSED, (uint64_t)(uintptr_t)this, ok ? 0u : 0xFFu);
	return ok;
}

// RDNA4FB's initForPM verbatim: three power states (0 sleep, 1 doze, 2 wake), system sleep VETOED from every state (the monitor B's pixels cannot be restored after the GPU loses power), registered with the policy maker, no sleep until
// the displays allow it, not below doze until system sleep. The only difference: the "IOPMIsPowerManaged" marker goes on our own provider (the nub), not on a PCI device.
void Navi48Framebuffer::initForPM() {
	N48_AUX_ENTER_V();
	if (pmRegistered) return;
	pmRegistered = true;
	static IOPMPowerState powerStates[3] = {
		{ 1, 0,                0,            0,            0, 0, 0, 0, 0, 0, 0, 0 },
		{ 1, 0,                0,            kIOPMPowerOn, 0, 0, 0, 0, 0, 0, 0, 0 },
		{ 1, kIOPMDeviceUsable, kIOPMPowerOn, kIOPMPowerOn, 0, 0, 0, 0, 0, 0, 0, 0 },
	};
	for (auto &state : powerStates) state.capabilityFlags |= kIOPMPreventSystemSleep;
	registerPowerDriver(this, powerStates, 3);
	temporaryPowerClampOn();
	changePowerStateTo(1);
	IOService *p = getProvider();
	if (p) p->setProperty("IOPMIsPowerManaged", true);
}

IOReturn Navi48Framebuffer::enableController() {
	N48_AUX_ENTER(kIOReturnNotReady);
	initForPM();
	if (dops && dops->trace) dops->trace(N48_DTR_ENABLE, (uint64_t)(uintptr_t)this, 0u);
	return kIOReturnSuccess;
}

IODeviceMemory *Navi48Framebuffer::getApertureRange(IOPixelAperture aperture) {
	N48_AUX_ENTER(nullptr);
	uint64_t phys = 0, len = 0;
	if (!fb_aperture(&snap, aperture == kIOFBSystemAperture, &phys, &len)) return nullptr;
	return IODeviceMemory::withRange((IOPhysicalAddress)phys, (IOPhysicalLength)len);      // a fresh instance (retained) per the caller's contract
}
IODeviceMemory *Navi48Framebuffer::getVRAMRange() {
	N48_AUX_ENTER(nullptr);
	uint64_t phys = 0, len = 0;
	if (!fb_aperture(&snap, true, &phys, &len)) return nullptr;
	return IODeviceMemory::withRange((IOPhysicalAddress)phys, (IOPhysicalLength)len);
}

const char *Navi48Framebuffer::getPixelFormats() {
	N48_AUX_ENTER(nullptr);
	static const char formats[] = IO32BitDirectPixels "\0";         // NUL-separated, double-NUL terminated
	return formats;
}
IOItemCount Navi48Framebuffer::getDisplayModeCount() {
	N48_AUX_ENTER(0);
	return fb_mode_count();
}
IOReturn Navi48Framebuffer::getDisplayModes(IODisplayModeID *allDisplayModes) {
	N48_AUX_ENTER(kIOReturnNotReady);
	if (!allDisplayModes) return kIOReturnBadArgument;
	allDisplayModes[0] = (IODisplayModeID)kFbModeId;
	return kIOReturnSuccess;
}
IOReturn Navi48Framebuffer::getInformationForDisplayMode(IODisplayModeID displayMode, IODisplayModeInformation *info) {
	N48_AUX_ENTER(kIOReturnNotReady);
	FbModeInfo m;
	if (!info || !fb_mode_info(&snap, (uint32_t)displayMode, &m)) return kIOReturnBadArgument;
	bzero(info, sizeof(*info));
	info->nominalWidth = m.w; info->nominalHeight = m.h; info->refreshRate = m.refresh1616; info->maxDepthIndex = (IOIndex)m.maxDepthIndex;
	info->flags = (m.valid ? kDisplayModeValidFlag : 0u) | (m.safe ? kDisplayModeSafeFlag : 0u) | (m.isDefault ? kDisplayModeDefaultFlag : 0u);
	return kIOReturnSuccess;
}
UInt64 Navi48Framebuffer::getPixelFormatsForDisplayMode(IODisplayModeID, IOIndex) {
	N48_AUX_ENTER(0);
	return 0;                                                       // obsolete: must return 0
}
IOReturn Navi48Framebuffer::getPixelInformation(IODisplayModeID displayMode, IOIndex depth, IOPixelAperture aperture, IOPixelInformation *pixelInfo) {
	N48_AUX_ENTER(kIOReturnNotReady);
	FbPixel p;
	if (!pixelInfo || depth < 0 || !fb_pixel_info(&snap, (uint32_t)displayMode, (uint32_t)depth, aperture == kIOFBSystemAperture, &p)) return kIOReturnBadArgument;
	bzero(pixelInfo, sizeof(*pixelInfo));
	pixelInfo->bytesPerRow = p.bytesPerRow; pixelInfo->bitsPerPixel = p.bitsPerPixel; pixelInfo->pixelType = kIORGBDirectPixels;
	pixelInfo->componentCount = p.componentCount; pixelInfo->bitsPerComponent = p.bitsPerComponent;
	for (unsigned i = 0; i < 3u; i++) pixelInfo->componentMasks[i] = p.masks[i];
	for (unsigned i = 0; i < sizeof(p.format) && i < sizeof(pixelInfo->pixelFormat); i++) pixelInfo->pixelFormat[i] = p.format[i];
	pixelInfo->activeWidth = p.w; pixelInfo->activeHeight = p.h;
	return kIOReturnSuccess;
}

IOReturn Navi48Framebuffer::getCurrentDisplayMode(IODisplayModeID *displayMode, IOIndex *depth) {
	N48_AUX_ENTER(kIOReturnNotReady);
	if (displayMode) *displayMode = (IODisplayModeID)kFbModeId;
	if (depth) *depth = 0;
	return kIOReturnSuccess;
}
IOReturn Navi48Framebuffer::getStartupDisplayMode(IODisplayModeID *displayMode, IOIndex *depth) {
	N48_AUX_ENTER(kIOReturnNotReady);
	if (displayMode) *displayMode = (IODisplayModeID)kFbModeId;      // the base getter returns 0xE00002C7
	if (depth) *depth = 0;
	return kIOReturnSuccess;
}
IOReturn Navi48Framebuffer::setDisplayMode(IODisplayModeID displayMode, IOIndex depth) {
	N48_AUX_ENTER(kIOReturnNotReady);
	if (dops && dops->trace) dops->trace(N48_DTR_SETMODE, (uint64_t)displayMode, (uint64_t)(int64_t)depth);
	return (depth >= 0 && fb_mode_ok((uint32_t)displayMode, (uint32_t)depth)) ? kIOReturnSuccess : kIOReturnUnsupported;      // only (1, 0)
}

IOReturn Navi48Framebuffer::getAttribute(IOSelect attribute, uintptr_t *value) {
	N48_AUX_ENTER(kIOReturnNotReady);
	const FbAttr a = fb_attr((uint32_t)attribute);              // 'crsr' = 0: the software cursor (no hardware cursor plane in M5)
	if (a.rc == kFbRcSuper) return IOFramebuffer::getAttribute(attribute, value);
	if (a.hasValue && value) *value = a.value;
	return kIOReturnSuccess;
}
IOReturn Navi48Framebuffer::setAttribute(IOSelect attribute, uintptr_t value) {
	N48_AUX_ENTER(kIOReturnNotReady);
	if (!fb_power_attr((uint32_t)attribute)) return IOFramebuffer::setAttribute(attribute, value);
	powerState = (uint32_t)value;                                // RECORDED only: no hardware action in M5 (the monitor B keeps its last image)
	if (dops && dops->power) (void)dops->power((void *)getProvider(), (uint32_t)value);
	if (dops && dops->trace) dops->trace(N48_DTR_POWER, (uint64_t)value, 0u);
	return kIOReturnSuccess;
}
IOItemCount Navi48Framebuffer::getConnectionCount() {
	N48_AUX_ENTER(0);
	return 1;
}
IOReturn Navi48Framebuffer::getAttributeForConnection(IOIndex connectIndex, IOSelect attribute, uintptr_t *value) {
	N48_AUX_ENTER(kIOReturnNotReady);
	const FbAttr a = fb_connection_attr(&snap, (uint32_t)attribute);
	if (a.rc == kFbRcSuper) return IOFramebuffer::getAttributeForConnection(connectIndex, attribute, value);
	if (a.rc == kFbRcUnsupported) return kIOReturnUnsupported;
	if (a.hasValue && value) *value = a.value;
	return kIOReturnSuccess;
}
IOReturn Navi48Framebuffer::setAttributeForConnection(IOIndex connectIndex, IOSelect attribute, uintptr_t value) {
	N48_AUX_ENTER(kIOReturnNotReady);
	if (!fb_power_attr((uint32_t)attribute)) return IOFramebuffer::setAttributeForConnection(connectIndex, attribute, value);
	connPower = (uint32_t)value;                                 // display-sleep path of IODisplay: RECORDED only
	return kIOReturnSuccess;
}

bool Navi48Framebuffer::hasDDCConnect(IOIndex connectIndex) {
	N48_AUX_ENTER(false);
	return fb_has_ddc(&snap, (int32_t)connectIndex);
}
IOReturn Navi48Framebuffer::getDDCBlock(IOIndex connectIndex, UInt32 blockNumber, IOSelect blockType, IOOptionBits, UInt8 *data, IOByteCount *length) {
	N48_AUX_ENTER(kIOReturnNotReady);
	const uint8_t *src = nullptr; uint64_t n = 0;
	const FbDdc r = fb_ddc_block(&snap, (int32_t)connectIndex, (uint32_t)blockNumber, blockType == kIODDCBlockTypeEDID, data != nullptr && length != nullptr, length ? (uint64_t)*length : 0u, &src, &n);
	if (r == kFbDdcUnsupported) return kIOReturnUnsupported;
	if (r == kFbDdcNotFound) return kIOReturnNotFound;
	memcpy(data, src, (size_t)n);
	*length = (IOByteCount)n;
	return kIOReturnSuccess;
}
